/* auto-generated by NAPI-RS */
/* eslint-disable */
/** 区域参数 */
export interface Area {
  /** 左上角X坐标 */
  x: number
  /** 左上角Y坐标 */
  y: number
  /** 宽度 */
  width: number
  /** 高度 */
  height: number
}

/** 截图所有显示器并合并为一张大图 */
export declare function captureAllDisplays(): ImageData

/** 截图指定区域（可能跨显示器） */
export declare function captureArea(area: Area): ImageData

/** 截图指定显示器 */
export declare function captureDisplay(displayId: string): ImageData | null

/** 显示器信息 */
export interface DisplayInfo {
  /** 显示器唯一ID */
  id: string
  /** 显示器名称 */
  name: string
  /** 显示器左上角X坐标 */
  x: number
  /** 显示器左上角Y坐标 */
  y: number
  /** 显示器宽度 */
  width: number
  /** 显示器高度 */
  height: number
  /** 缩放因子 (DPI缩放) */
  scaleFactor: number
  /** 是否为主显示器 */
  isPrimary: boolean
}

/** 获取所有显示器信息 */
export declare function getDisplays(): Array<DisplayInfo>

/** 图像数据 */
export interface ImageData {
  /** PNG编码的图像数据 */
  data: Buffer
  /** 图像宽度 */
  width: number
  /** 图像高度 */
  height: number
}

/** 将图像数据保存为文件 */
export declare function saveToFile(data: Buffer, path: string): void
